# Generated by Django 3.0.6 on 2020-06-23 13:01

from django.db import migrations, models
import shipping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[shipping.models.validate_phone])),
                ('shipping_option', models.SmallIntegerField(choices=[(10, 'Free shipping'), (20, 'Express shipping'), (30, 'Courier shipping')], default=10)),
            ],
        ),
    ]
