# Generated by Django 3.0.6 on 2020-06-22 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shipping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[shipping.models.validate_phone])),
                ('shipping_option', models.SmallIntegerField(choices=[(10, 'Free shipping'), (20, 'Express shipping'), (30, 'Courier shipping')], default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
